apiVersion: v1
kind: ConfigMap
metadata:
  # Must match the 'spring.application.name' property of the application
  name: ${project.artifactId}
  app: ${project.artifactId}
data:
  application.properties: |
    # Override the configuration properties here
    quickstart.recipients=direct:async-queue,direct:file,direct:mail
    greeter.prefix=Hello
    greeter.message=%s! Spring Boot application.properties has been mounted as volume on OpenShift!