apiVersion: v1
kind: ConfigMap
metadata:
  # Must match the 'spring.application.name' property of the application
  name: ${project.artifactId}
  app: ${project.artifactId}
data:
  application.yml: |-
    quickstart:
      recipients: direct:async-queue,direct:file
    greeter:
      prefix: Hello dev
      message: "%s! Spring Boot application.yml has been mounted as volume on OpenShift dev!"
    ---
    spring:
      profiles: development
    greeter:
      prefix: Hello dev
      message: "%s! Spring Boot application.yml has been mounted as volume on OpenShift dev!"
    ---
    spring:
      profiles: production
    greeter:
      prefix: Hello prod
      message: "%s! Spring Boot application.yml has been mounted as volume on OpenShift prod!"