apiVersion: v1
kind: RoleBinding
metadata:
  name: ${project.artifactId}
roleRef:
  # Add the view role to the service account
  name: view
subjects:
  - kind: ServiceAccount
    name: ${project.artifactId}