---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    expose: "true"
    app: ${project.artifactId}
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.redhat
  name: ${project.artifactId}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ${project.artifactId}
