server:
  address: 0.0.0.0
  port: 8080

management:
  server:
  address: 0.0.0.0
  port: 8081
  security.enabled: false

endpoints:
  enabled: true
  health.enabled: true
  camelhealthchecks.enabled: true

camel:
  springboot:
    # The Camel context name
    name: spring-boot-swagger

  component:
    servlet:
      mapping:
        contextPath: /spring-boot-swagger

  health:
    indicator.enabled: true
    check:
      service.enabled: true
      indicator.enabled: true
      routes.enabled: true