# Default quickstart configuration (overridden at runtime using ConfigMaps and Secrets)
quickstart:
  recipients: direct:async-queue,direct:file
  queue-username: wrong-username
  queue-password: wrong-password

# Startup configuration of Spring-cloud-kubernetes
spring:
  application:
    name: spring-boot-camel-swagger-ui
  cloud:
    kubernetes:
      reload:
        # Enable live reload on ConfigMap change (disabled for Secrets by default)
        enabled: true
      secrets:
        paths: /etc/secrets/spring-boot-camel-swagger-ui

server:
  address: 0.0.0.0
  port: 8080

management:
  server:
  address: 0.0.0.0
  port: 8081
  security.enabled: false

endpoints:
  enabled: true
  health.enabled: true
  camelhealthchecks.enabled: true

camel:
  springboot:
    # The Camel context name
    name: spring-boot-swagger

  component:
    servlet:
      mapping:
        contextPath: /spring-boot-swagger

  health:
    indicator.enabled: true
    check:
      service.enabled: true
      indicator.enabled: true
      routes.enabled: true

