# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v2.3.4
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2.3.0
      with:
        java-version: 8
        distribution: 'adopt'
 
    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      env:
        cache-name: cache-mvn
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
      
    - name: Test with Maven
      run: mvn -B test --file pom.xml
